import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from app.config import settings

SECRET_KEY = settings.ENCRYPTION_KEY

def get_fernet():
    try:
        # If the key is already a valid Fernet key (like the one generated by the user)
        # we can use it directly.
        return Fernet(SECRET_KEY.encode())
    except Exception:
        # If not, we derive a key using KDF for backward compatibility/flexibility
        salt = b'byteforge_salt_2026'
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=100000,
        )
        key = base64.urlsafe_b64encode(kdf.derive(SECRET_KEY.encode()))
        return Fernet(key)

cipher = get_fernet()

def encrypt_data(data: str) -> str:
    """Encrypts a string into a base64 encoded token."""
    if not data:
        return data
    return cipher.encrypt(data.encode()).decode()

def decrypt_data(token: str) -> str:
    """Decrypts a base64 encoded token back to string."""
    if not token:
        return token
    try:
        return cipher.decrypt(token.encode()).decode()
    except Exception:
        # Fallback for unencrypted data during transition or corrupted data
        return "[ENCRYPTION_ERROR]"
